name: clash-draw-toy
version: 0.1.0
category: acme

dependencies:
  - base
  - clash-prelude
  - clash-lib
  - clash-ghc
  - ghc-typelits-natnormalise
  - ghc-typelits-extra
  - ghc-typelits-knownnat

  - retroclash-lib
  - retroclash-sim

  - shake
  - microstache
  - lens
  - mtl
  - transformers
  - sdl2
  - text
  - array
  - extra

# Anything that Clash uses by default should go here
default-extensions:
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DeriveLift
  - DerivingStrategies
  - ExplicitForAll
  - ExplicitNamespaces
  - FlexibleContexts
  - FlexibleInstances
  - KindSignatures
  - MagicHash
  - MonoLocalBinds
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - NoStarIsType
  - NoStrictData
  - NoStrict
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskellQuotes
  - TemplateHaskell
  - TypeApplications
  - TypeFamilies
  - TypeInType
  - TypeOperators

ghc-options:
  -fplugin GHC.TypeLits.KnownNat.Solver
  -fplugin GHC.TypeLits.Normalise
  -fplugin GHC.TypeLits.Extra.Solver

source-dirs:
  - src

flags:
  verilator:
    manual: True
    default: False

executables:
  # draw-toy:
  #   main: simulator.hs

  draw-toy-verilator:
    main: verilator.hs
    when:
    - condition: flag(verilator)
      then:
        dependencies:
          - clashilator-ffi
      else:
        buildable: false
