resolver: clash-HEAD.yaml

extra-deps:
  - clash-shake
  - retroclash-lib
  - retroclash-sim

  - barbies-2.0.1.0
  - github: fumieval/barbies-th
    commit: 040aac815b712d4cd2a9fa0990e8b0e23481a215

  - github: gergoerdi/clashilator
    commit: 16373f805ad4006f629701bdfd1c37906d0f667b
