resolver: clash-HEAD.yaml

extra-deps:
  - clash-shake
  - retroclash-lib
  - retroclash-sim

  - barbies-2.0.1.0
  - github: gergoerdi/barbies-th
    commit: af2335de760b02ad6dcaff1db29c1055b5202c1d

  - github: gergoerdi/clashilator
    commit: 16373f805ad4006f629701bdfd1c37906d0f667b
